---
title: "datafeature"
author: "Shiyu Tong"
date: "2022-11-16"
output: html_document
---

```{r}
filepath <- "data/"
raw_data <- read.csv(paste0(filepath,"geothermal.csv"))

```


```{r}
head(raw_data)
top_countries <- names(sort(table(raw_data['affiliation.country']),decreasing = TRUE)[1:20])
rank = sort(table(raw_data['affiliation.country']),decreasing = TRUE)[1:15]
plot(rank)
pie(rank, main="Pie Chart of Countries")
```


```{r}
select_data <- raw_data[raw_data$affiliation.country %in% top_countries,]
# new zealand avg rank
x = select_data$affiliation.country == 'New Zealand'
mean(which(x == TRUE))
hist(which(x == TRUE),main = "New Zealand rank distribution",xlab = 'Rank index')
# USA avg rank
x = select_data$affiliation.country == 'United States'
mean(which(x == TRUE))
hist(which(x == TRUE),main = "USA rank  distribution",xlab = 'Rank index')
# CHINA avg rank
x = select_data$affiliation.country == 'China'
mean(which(x == TRUE))
hist(which(x == TRUE),main = "CHINA rank  distribution",xlab = 'Rank index')
```


Do T test among countires

```{r}
# NZ Rank
X <- select_data$affiliation.country == 'New Zealand'
NZ_rank <- which(X == TRUE)
X <- select_data$affiliation.country == 'United States'
USA_rank <- which(X == TRUE)
X <- select_data$affiliation.country == 'China'
CH_rank <- which(X == TRUE)

```


```{r}
t.test(NZ_rank,USA_rank)
t.test(NZ_rank,CH_rank)
```

The T test result of NZ and USA. The p-value is 0.022. Smaller than 0.05. So it means that there is a difference between NZ and USA.

On the other hand. There is no difference between NZ and China.

### Check distribution




### Use all data
```{r}
filepath = 'data/selected/'
filelist <- list.files(filepath)
filelist
raw_data <- data.frame()
for (file in filelist){
  #cat(file)
  data <- read.csv(paste0(filepath, file))
  raw_data <- rbind(raw_data,data)
}
```


```{r}
top_countries <- names(sort(table(raw_data['affiliation.country']),decreasing = TRUE)[1:30])
rank = sort(table(raw_data['affiliation.country']),decreasing = TRUE)[1:15]
plot(rank)
pie(rank, main="Pie Chart of Countries")

```

```{r}
GDP_data <- read.csv('data/GDP_data.csv')
#summary(GDP_data)
country_list <- c('United States','New Zealand','China','United Kingdom','France','India','Australia')
GDP_data = GDP_data[which(GDP_data$Country.Name %in% country_list),]
```

```{r}
# Using avg GDP 2000-2021
GDP_data = GDP_data[,colnames(GDP_data)[c(1:2,45:66)]]
GDP_data$avg_gdp <- rowMeans(GDP_data[,3:24])
GDP_data$avg_gdp <- GDP_data$avg_gdp / 10e9
```


```{r}
country_count <- table(raw_data['affiliation.country'])[country_list]
country_gdp_rate <- c()

for (country in country_list){
  country_gdp_rate <- c(country_gdp_rate,country_count[country]/GDP_data[which(GDP_data$Country.Name==country),'avg_gdp'])
}
country_gdp_rate
```

value for each topic

### Researcher Population
```{r}
researchers <- read.csv('data/Researchers.csv')
researchers_mean <- aggregate(researchers$Value, list(researchers$LOCATION), FUN=mean) 
country_list <- c('China','Germany','France','United Kingdom','New Zealand')
country_count <- table(raw_data['affiliation.country'])[country_list]
```


```{r}
colnames(researchers_mean) <- c('country','researchers_mean')
researchers_mean$country <- country_list
country_researcher_rate <- c()

for (country in country_list){
  country_researcher_rate <- c(country_researcher_rate,country_count[country]/researchers_mean[which(researchers_mean$country==country),'researchers_mean'])
}
country_researcher_rate
```


### University Count
```{r}
library(dplyr)
country_list <- c('United States','New Zealand','China','United Kingdom','France','India','Australia','Germany')
university_count <- raw_data[which(raw_data$affiliation.country %in% country_list),]
university_count <- aggregate(university_count$affilname,list(university_count$affiliation.country,university_count$affilname),FUN = length )
colnames(university_count) <- c('country','university','count')
university_count <- aggregate(university_count$university,list(university_count$country),FUN = length )
colnames(university_count) <- c('country','value')
paper_count <- table(raw_data['affiliation.country'])[country_list]
```

```{r}
country_uni_rate <- c()
for (country in country_list){
  country_uni_rate <- c(country_uni_rate,paper_count[country]/university_count[which(university_count$country==country),'value'])
}
country_uni_rate
```



### average citetion count
```{r}
select_data <- raw_data[which(raw_data$affiliation.country %in% country_list),]
aggregate(select_data$citedby_count,list(select_data$affiliation.country),FUN = mean)
```

### Compare QS TOP500

```{r}
filepath = 'data/QSrank.csv'
QS500 <- read.csv(filepath,header = TRUE)
QS500 <- QS500[1:500,5:7]
# re <- c('China (Mainland)','Hong Kong SAR', 'Taiwan')
QS500[QS500$country == 'China (Mainland)','country'] <- 'China'
country_list <- c('United States','New Zealand','China','United Kingdom','France','India','Australia','Germany')
QS500 <- QS500[which(QS500$country %in% country_list),'institution']
uni_selected <- raw_data[which(raw_data$affilname %in% QS500),]
unique(uni_selected[which(uni_selected$affiliation.country == 'New Zealand'),'affilname'])
```


```{r}
uni_count <- aggregate(uni_selected$affilname,list(uni_selected$affiliation.country,uni_selected$affilname),FUN = length )
colnames(uni_count) <- c('Country','University','Count')
uni_count <- aggregate(uni_count$University,list(uni_count$Country),FUN = length)
colnames(uni_count) <- c('Country','Count')
paper_count <- table(uni_selected$affiliation.country)


country_QS500_rate <- c()
for (country in country_list){
  country_QS500_rate <- c(country_QS500_rate,paper_count[country]/uni_count[which(uni_count$Country==country),'Count'])
}
sort(country_QS500_rate,decreasing = TRUE)
```



