---
title: "PrimaryAnalysis"
author: "Shiyu Tong"
date: "2023-03-20"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(gridExtra)
infilepath <- 'data/raw_data/'
```


```{r}
filelist <- list.files(infilepath)
raw_data <- data.frame()
for (file in filelist){
  #cat(file)
  data <- read.csv(paste0(infilepath, file))
  data$topic <- gsub('.csv','',file)
  raw_data <- rbind(raw_data,data)
}
rm(data)
```

```{r}
# TOP 5 GDP countries with NZ
country_list <- c('United States','China','Japan','Germany','United Kingdom','New Zealand')
# Similiar countries with NZ
SAEs <- c('Denmark','Finland','Singapore','Israel','Norway','New Zealand')
```



```{r}
GDP_data <- read.csv('data/GDP_data.csv')
GDP_data = GDP_data[,colnames(GDP_data)[c(1:2,45:65)]]
GDP_data$avg_gdp <- rowMeans(GDP_data[,3:23])
#avg GDP unit: billion US dollar
GDP_data$avg_gdp <- GDP_data$avg_gdp / 10e9
GDP_data <- GDP_data[which(GDP_data$Country.Name %in% c(country_list,SAEs)),]
GDP_data <- GDP_data[order(GDP_data$avg_gdp ,decreasing = TRUE),]
```

```{r}
##  先计算每年投入，再计算平均值
RND_data_pp <- read.csv('data/Research and development expenditure.csv',header = TRUE)
RND_data_pp = RND_data_pp[,colnames(RND_data_pp)[c(1:2,45:65)]]
RND_data_pp <- RND_data_pp[which(RND_data_pp$Country.Name %in% c(country_list,SAEs)),]
RND_data_pp <- RND_data_pp[order(RND_data_pp$Country.Name ,decreasing = TRUE),]
RND_data <- GDP_data[,c(1:2)] 
results <- GDP_data[,c(3:23)] * RND_data_pp[,c(3:23)] / 100
RND_data <- cbind(RND_data,results)
# unit : billion US dollar 20 years average data
RND_data$avg_rnd <- rowMeans(RND_data[,3:23],na.rm = TRUE)
RND_data$avg_rnd <- RND_data$avg_rnd /10e9
```

```{r}
filepath = 'data/QSrank.csv'
QS500 <- read.csv(filepath,header = TRUE)
QS500 <- QS500[1:500,5:7]
QS500[QS500$country == 'China (Mainland)','country'] <- 'China'
QS500 <- QS500[which(QS500$country %in% c(country_list,SAEs) ),c('institution','country')]
QS500[QS500$institution == 'National University of Singapore (NUS)','institution'] <- 'National University of Singapore'
QS500[QS500$institution == 'Nanyang Technological University, Singapore (NTU)','institution'] <- 'Nanyang Technological University'
raw_data[raw_data$affilname == 'Universitetet i Oslo','affilname'] <- 'University of Oslo'
raw_data[raw_data$affilname == 'Universitetet i Bergen','affilname'] <- 'University of Bergen'
raw_data[raw_data$affilname == 'Norges Teknisk-Naturvitenskapelige Universitet','affilname'] <- 'University of Bergen'
raw_data[raw_data$affilname == 'UiT Norges Arktiske Universitet','affilname'] <- 'University of Tromsø The Arctic University of Norway'
uni_selected <- raw_data[which(raw_data$affilname %in% QS500[,'institution']),]
unique(uni_selected[which(uni_selected$affiliation.country == 'New Zealand'),'affilname'])
```

```{r}
country_count <- table(raw_data['affiliation.country'])[country_list]
country_gdp_rate <- c()
for (country in country_list){
  country_gdp_rate <- c(country_gdp_rate,country_count[country]/GDP_data[which(GDP_data$Country.Name==country),'avg_gdp'])
}
country_gdp_rate <- data.frame(country = names(country_gdp_rate),rate = country_gdp_rate,row.names = 1:length(country_gdp_rate))
#png(paste0(outputpath,keyword,' GDP rate.png'))
ggplot(data=country_gdp_rate,aes(x = country, y= rate)) + 
  geom_bar(stat = 'identity') + 
  geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") + 
  labs(title = 'GDP rate for whole data in TOP GDP Country',x='Country','') +
  theme(plot.title = element_text(hjust = 0.5))
# ggsave(
#   filename = 'GDP rate for whole data in TOP GDP Country.png'
# )
```


```{r}
# TOP GDP countries
topics <- unique(raw_data$topic)

outputpath <- 'plots/'
for (keyword in topics){
    temp_data <- raw_data[which(raw_data$topic == keyword & raw_data$affiliation.country %in% country_list),]
    country_count <- table(temp_data['affiliation.country'])[country_list]
    # GDP rate
    country_gdp_rate <- c()
    for (country in country_list){
      country_gdp_rate <- c(country_gdp_rate,country_count[country]/GDP_data[which(GDP_data$Country.Name==country),'avg_gdp'])
    }
    country_gdp_rate <- data.frame(country = names(country_gdp_rate),rate = country_gdp_rate,
                                   row.names = NULL)
    p1 <- ggplot(data=country_gdp_rate,aes(x = country, y= rate)) + 
      geom_bar(stat = 'identity') + 
      geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") + 
      labs(title = ' GDP rate in top GDP Country',x='Country', subtitle = keyword,y = 'Paper Amount / GDP(billion US dollar)') +
      theme(plot.title = element_text(hjust = 0.5))
    
    # RND rate 
    country_rnd_rate <- c()
    for (country in country_list){
       country_rnd_rate <- c(country_rnd_rate,country_count[country]/RND_data[which(RND_data$Country.Name==country),'avg_rnd'])
    }
    rnd_rate <- data.frame(country = c(names(country_rnd_rate)), 
                                       rate = c(country_rnd_rate),row.names = NULL)
    p2 <- ggplot(data=rnd_rate,aes(x = country, y= rate)) + 
      geom_bar(stat = 'identity') +
      geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") +
      labs(title = ' R&D rate in Top GDP countries', x= 'Country',y = 'Paper Åmount / R&D(billion US dollar)',subtitle = keyword) +
      theme(plot.title = element_text(hjust = 0.5))
    
    # QS 500 university count ，paper-count/university-count
    uni_selected <- raw_data[which(raw_data$affilname %in% QS500[,'institution']),]
    uni_selected <- uni_selected[which(uni_selected$topic == keyword),]
    uni_count <- aggregate(uni_selected$affilname,list(uni_selected$affiliation.country,uni_selected$affilname),FUN = length )
    colnames(uni_count) <- c('Country','University','Count')
    uni_count <- aggregate(uni_count$University,list(uni_count$Country),FUN = length)
    colnames(uni_count) <- c('Country','Count')
    paper_count <- table(uni_selected$affiliation.country)
    country_QS500_rate <- c()
    for (country in country_list){
      country_QS500_rate <- c(country_QS500_rate,paper_count[country]/uni_count[which(uni_count$Country==country),'Count'])
    }
    qs_rate = data.frame(country = c(names(country_QS500_rate)), 
                                       rate = c(country_QS500_rate),row.names = NULL)
    p3 <- ggplot(data=qs_rate,aes(x = country, y= rate)) + 
      geom_bar(stat = 'identity') + 
      geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") + 
      labs(title = ' QS500 rate in Top GDP countries', x= 'Country',y = 'Paper Åmount / QS500 Uni Amount',subtitle = keyword) +
      theme(plot.title = element_text(hjust = 0.5))
    
    
    # avg cititation count all-paper(cititation-count)/
    select_data <- temp_data[which(temp_data$affiliation.country %in% country_list),]
    avg_cite <- aggregate(select_data$citedby_count,list(select_data$affiliation.country),FUN = mean)
    colnames(avg_cite) <- c('country','avg_count')
    p4 <- ggplot(data=avg_cite,aes(x = country, y= avg_count)) + 
      geom_bar(stat = 'identity') + 
      geom_text(aes(label = round(avg_count,2)), vjust = 1.5, colour = "white") + 
      labs(title = ' Average cititation num in Top GDP countries', x= 'Country',y = 'Average citation num',subtitle = keyword) +
      theme(plot.title = element_text(hjust = 0.5))
    print(p1)
    print(p2)
    print(p3)
    print(p4)
    ggsave(paste0(outputpath,keyword,' GDP Rate in Top GDP Country.png'),plot = p1)
    ggsave(paste0(outputpath,keyword,' R&D Rate in Top GDP Country.png'),plot = p2)
    ggsave(paste0(outputpath,keyword,' QS500 Uni Rate in Top GDP Country.png'),plot = p3)
    ggsave(paste0(outputpath,keyword,' Average citation in Top GDP Country.png'),plot = p4)
    
    
}
```

```{r}
# SAEs
topics <- unique(raw_data$topic)

outputpath <- 'plots/'
for (keyword in topics){
    temp_data <- raw_data[which(raw_data$topic == keyword & raw_data$affiliation.country %in% SAEs),]
    country_count <- table(temp_data['affiliation.country'])[SAEs]
    # GDP rate
    country_gdp_rate <- c()
    for (country in SAEs){
      country_gdp_rate <- c(country_gdp_rate,country_count[country]/GDP_data[which(GDP_data$Country.Name==country),'avg_gdp'])
    }
    country_gdp_rate <- data.frame(country = names(country_gdp_rate),rate = country_gdp_rate,
                                   row.names = NULL)
    p1 <- ggplot(data=country_gdp_rate,aes(x = country, y= rate)) + 
      geom_bar(stat = 'identity') + 
      geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") + 
      labs(title = ' GDP rate in SAEs',x='Country', subtitle = keyword,y = 'Paper Amount / GDP(billion US dollar)') +
      theme(plot.title = element_text(hjust = 0.5))
    
    # R&D rate
    country_rnd_rate <- c()
    for (country in SAEs){
       country_rnd_rate <- c(country_rnd_rate,country_count[country]/RND_data[which(RND_data$Country.Name==country),'avg_rnd'])
    }
    rnd_rate <- data.frame(country = c(names(country_rnd_rate)), 
                                       rate = c(country_rnd_rate),row.names = NULL)
    p2 <- ggplot(data=rnd_rate,aes(x = country, y= rate)) + 
      geom_bar(stat = 'identity') +
      geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") +
      labs(title = ' R&D rate in SAEs', x= 'Country',y = 'Paper Åmount / R&D(billion US dollar)',subtitle = keyword) +
      theme(plot.title = element_text(hjust = 0.5))
    # QS 500 university count
    uni_selected <- raw_data[which(raw_data$affilname %in% QS500[,'institution']),]
    uni_selected <- uni_selected[which(uni_selected$topic == keyword),]
    uni_count <- aggregate(uni_selected$affilname,list(uni_selected$affiliation.country,uni_selected$affilname),FUN = length )
    colnames(uni_count) <- c('Country','University','Count')
    uni_count <- aggregate(uni_count$University,list(uni_count$Country),FUN = length)
    colnames(uni_count) <- c('Country','Count')
    paper_count <- table(uni_selected$affiliation.country)
    country_QS500_rate <- c()
    for (country in SAEs){
      country_QS500_rate <- c(country_QS500_rate,paper_count[country]/uni_count[which(uni_count$Country==country),'Count'])
    }
    qs_rate = data.frame(country = c(names(country_QS500_rate)), 
                                       rate = c(country_QS500_rate),row.names = NULL)
    p3 <- ggplot(data=qs_rate,aes(x = country, y= rate)) + 
      geom_bar(stat = 'identity') + 
      geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") + 
      labs(title = ' QS500 rate in SAEs', x= 'Country',y = 'Paper Åmount / QS500 Uni Amount',subtitle = keyword) +
      theme(plot.title = element_text(hjust = 0.5))
    # avg cititation count
    select_data <- temp_data[which(temp_data$affiliation.country %in% SAEs),]
    avg_cite <- aggregate(select_data$citedby_count,list(select_data$affiliation.country),FUN = mean)
    colnames(avg_cite) <- c('country','avg_count')
    p4 <- ggplot(data=avg_cite,aes(x = country, y= avg_count)) + 
      geom_bar(stat = 'identity') + 
      geom_text(aes(label = round(avg_count,2)), vjust = 1.5, colour = "white") + 
      labs(title = ' Average cititation num in SAEs', x= 'Country',y = 'Average citation num',subtitle = keyword) +
      theme(plot.title = element_text(hjust = 0.5))
    print(p1)
    print(p2)
    print(p3)
    print(p4)
    ggsave(paste0(outputpath,keyword,' GDP Rate in SAEs.png'),plot = p1)
    ggsave(paste0(outputpath,keyword,' R&D Rate in SAEs.png'),plot = p2)
    ggsave(paste0(outputpath,keyword,' QS500 Uni Rate in SAEs.png'),plot = p3)
    ggsave(paste0(outputpath,keyword,' Average citation in SAEs.png'),plot = p4)
}


```





```{r}
country_count <- table(raw_data['affiliation.country'])[country_list]
# GDP rate
country_gdp_rate <- c()
for (country in country_list){
  country_gdp_rate <- c(country_gdp_rate,country_count[country]/GDP_data[which(GDP_data$Country.Name==country),'avg_gdp'])
}
country_gdp_rate <- data.frame(country = names(country_gdp_rate),rate = country_gdp_rate,
                               row.names = NULL)
p1 <- ggplot(data=country_gdp_rate,aes(x = country, y= rate)) + 
  geom_bar(stat = 'identity') + 
  geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") + 
  labs(title = 'GDP rate for whole data in TOP GDP Country',x='Country','') +
  theme(plot.title = element_text(hjust = 0.5))

# RND rate
country_rnd_rate <- c()
for (country in country_list){
   country_rnd_rate <- c(country_rnd_rate,country_count[country]/RND_data[which(RND_data$Country.Name==country),'avg_rnd'])
}
rnd_rate <- data.frame(country = c(names(country_rnd_rate)), 
                                   rate = c(country_rnd_rate),row.names = NULL)
p2 <- ggplot(data=rnd_rate,aes(x = country, y= rate)) + 
  geom_bar(stat = 'identity') +
  geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") +
  labs(title = 'RND rate in TOP GDP countries') +
  theme(plot.title = element_text(hjust = 0.5))
# QS 500 university count
uni_selected <- raw_data[which(raw_data$affilname %in% QS500[,'institution']),]
uni_count <- aggregate(uni_selected$affilname,list(uni_selected$affiliation.country,uni_selected$affilname),FUN = length )
colnames(uni_count) <- c('Country','University','Count')
uni_count <- aggregate(uni_count$University,list(uni_count$Country),FUN = length)
colnames(uni_count) <- c('Country','Count')
paper_count <- table(uni_selected$affiliation.country)
country_QS500_rate <- c()
for (country in country_list){
  country_QS500_rate <- c(country_QS500_rate,paper_count[country]/uni_count[which(uni_count$Country==country),'Count'])
}
qs_rate = data.frame(country = c(names(country_QS500_rate)), 
                                   rate = c(country_QS500_rate),row.names = NULL)
p3 <- ggplot(data=qs_rate,aes(x = country, y= rate)) + 
  geom_bar(stat = 'identity') + 
  geom_text(aes(label = round(rate,2)), vjust = 1.5, colour = "white") + 
  labs(title = 'QS 500 rate for whole data in TOP Country',x='Country','') +
  theme(plot.title = element_text(hjust = 0.5))
# avg cititation count
select_data <- raw_data[which(raw_data$affiliation.country %in% country_list),]
avg_cite <- aggregate(select_data$citedby_count,list(select_data$affiliation.country),FUN = mean)
colnames(avg_cite) <- c('country','avg_count')
p4 <- ggplot(data=avg_cite,aes(x = country, y= avg_count)) + 
  geom_bar(stat = 'identity') + 
  geom_text(aes(label = round(avg_count,2)), vjust = 1.5, colour = "white") + 
  labs(title = 'Average cititation count for whole data in TOP Country',x='Country','') +
  theme(plot.title = element_text(hjust = 0.5))
p1
p2
p3
p4
```

```{r}
# NON QS 500 Rate
full_list <- c(country_list,SAEs)
full_list <- unique(full_list)
full_paper_count <- table(raw_data['affiliation.country'])[full_list]
uni_selected <- raw_data[which(raw_data$affilname %in% QS500[,'institution']),]
qs_paper_count <- table(uni_selected['affiliation.country'])[full_list]
non_qs_rate <- 1 - qs_paper_count/full_paper_count
full_paper_count
qs_paper_count
round(non_qs_rate,2)

```

```{r}
# test section
keyword <-'geothermal'
# QS 500 university count
countryname = 'China'
length(which(raw_data$affiliation.country == countryname))
uni_selected <- raw_data[which(raw_data$affilname %in% QS500[,'institution']),]
length(which(uni_selected$affiliation.country == countryname))
# nz_data <- raw_data[which(raw_data$affiliation.country == 'New Zealand'),]
# aggregate(nz_data$doi~nz_data$affilname,FUN = length)



```

```{r}
# GDP vs Paper amount
paper_count <- as.data.frame(paper_count)
colnames(paper_count) <- c('Country','paper_amount')
GDP_Paper <- merge(GDP_data,paper_count, by.x = 'Country.Name',by.y = 'Country')
GDP_Paper <- GDP_Paper[c('Country.Name','avg_gdp','paper_amount')]

p <- ggplot(GDP_Paper, aes(x=reorder(Country.Name,avg_gdp))) +
  geom_bar(aes(y=avg_gdp),stat = 'identity', fill = 'grey',group = 1) + 
  geom_line(aes(y=paper_amount/4.5),color = 'red',group = 2) + 
  scale_y_continuous(name = "GDP (2000-2021, Billion US Dollar)",sec.axis = sec_axis(~.*4.5, name="Paper Amount (All Keywords)")) +
  coord_flip() +
  labs(title = 'GDP vs Paper Amount',x = 'Country') +
  theme(axis.title.x.top = element_text(color = "red"),axis.text.x.top = element_text(color = 'red'))

print(p)
ggsave(paste0(outputpath,'GDP vs Paper Amount.png'),plot = p)
```

```{r}
# RND vs Paper Amount
RND_Paper <- merge(RND_data,paper_count, by.x = 'Country.Name',by.y = 'Country')
RND_Paper <- RND_Paper[c('Country.Name','avg_rnd','paper_amount')]

p <- ggplot(RND_Paper, aes(x=reorder(Country.Name,avg_rnd))) +
  geom_bar(aes(y=avg_rnd),stat = 'identity', fill = 'grey',group = 1) + 
  geom_line(aes(y=paper_amount/1.6),color = 'red',group = 2) + 
  scale_y_continuous(name = "R&D (2000-2020, Billion US Dollar)",sec.axis = sec_axis(~.*1.6, name="Paper Amount (All Keywords)")) +
  coord_flip() +
  labs(title = 'R&D vs Paper Amount',x = 'Country') +
  theme(axis.title.x.top = element_text(color = "red"),axis.text.x.top = element_text(color = 'red')) + 
  geom_text(aes(y = 7200, label = paper_amount, vjust=-0.5), col = "red") +
  geom_text(aes(y = avg_rnd, label = round(avg_rnd,2), vjust=-0.5), col = "black")

print(p)
ggsave(paste0(outputpath,'R&D vs Paper Amount.png'),plot = p)
```


```{r}
# basic data overview
p <- ggplot(data = GDP_data, mapping = aes(x = Country.Name,y = avg_gdp)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  labs(title = "Average GDP for each country(US-billion dollar,2000-2021)",x = 'Country', y= 'GDP value') 
p
ggsave(paste0(outputpath,'Average GDP for each country.png'),plot = p)

#R&D
p <- ggplot(data = RND_data, mapping = aes(x = Country.Name,y = avg_rnd)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  labs(title = "Average R&D for each country(US-billion dollar,2000-2020)",x = 'Country', y= 'R&D value') 
p
ggsave(paste0(outputpath,'Average R&D for each country.png'),plot = p)

QS_count <- aggregate(QS500$institution~QS500$country ,FUN = length)
colnames(QS_count) <- c('country','uni_count')

p <- ggplot(data = QS_count, mapping = aes(x = country,y = uni_count)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  labs(title = "QS Top 500 University for each country(QS 2021 Version)",x = 'Country', y= 'University Count') 
p
ggsave(paste0(outputpath,'QS500 count for each country.png'),plot = p)



```
